@startuml
actor "Infected User" as U

participant "Installer (C Program)" as Installer
participant "Backdoor Executable (C Program)" as Backdoor
participant "Backend Server" as Backend

U -> Installer: Run Installer
Installer -> Installer: Download Python Standalone
Installer -> Installer: Install Python Standalone Locally
Installer -> Installer: Download Backdoor Executable
Installer -> Installer: Save Files to Hidden Directory
Installer -> Backdoor: Launch Backdoor Executable

Backdoor -> Backend: Connect to Backend Server
Backend --> Backdoor: Send info retrieving payload (python code)
Backdoor -> Backend: Execute and Send back output

loop Continuous Communication
    Backend --> Backdoor: Send More Python Commands
    Backdoor -> Backend: Execute Python Code And Send Output
end

@enduml
