services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      
    volumes:
      - ./admin-panel:/app
      - /app/node_modules/
    ports:
      - "3000:5173"
    command: npm run dev
  