services:
  openvpn:
    image: openvpn/openvpn-as
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    ports:
      - 943:943 
      - 443:443
      - "1195:1194/udp"  # OpenVPN default port for VPN connections
    volumes:
      - ./openvpn-data/conf:/etc/openvpn  # Mount the OpenVPN configuration
      - ./openvpn-data/data:/openvpn
    environment:
      - DEBUG=1
    restart: unless-stopped
    networks:
      vpn_network:
        ipv4_address: 10.10.0.5  # Updated to a new IP

  python_server:
    container_name: python_server
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - TZ=Europe/Paris
    ports:
      - "4242:4242"   # Application port exposed for external access
      - "8000:8443"   # Application port exposed for external access
    volumes:
      - ./src:/app/src/
      - ./venv:/app/venv
      - ./storage:/storage
    networks:
      - vpn_network   # Connect the Python server to the VPN network

networks:
  vpn_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16  # Updated to a new subnet range
