FROM nginx:alpine
RUN apk add --no-cache openssl
RUN mkdir -p /certs && \
    openssl req -x509 -newkey rsa:4096 -nodes \
    -out /certs/cert.pem \
    -keyout /certs/key.pem \
    -days 365 \
    -subj '/CN=localhost'

COPY nginx.conf /etc/nginx/conf.d/default.conf