services:
  python_server:
    container_name: python_server
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - TZ=Europe/Paris
    ports:
      - "4242:4242"   # Application port exposed for external access
      - "8000:8443"   # Application port exposed for external access
    volumes:
      - ./src:/app/src/
      - ./venv:/app/venv
      - ./storage:/storage
