services:
  python_server:
    container_name: python_server
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - TZ=Europe/Paris
    ports:
      - "4242:4242"
      - "8000:8443"
    volumes:
      - ./src:/app/src/
      - ./venv:/app/venv
      - ./storage:/storage
      - ntlms:/responder_logs
  responder:
    container_name: responder
    build:
      context: .
      dockerfile: Dockerfile.responder
    environment:
      - TZ=Europe/Paris
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ntlms:/opt/Responder/logs
  fileserver:
    build:
      context: .
      dockerfile: Dockerfile.fileserver
    ports:
      - "8080:8080"
    volumes:
      - ./files:/usr/share/nginx/html:ro
volumes:
  ntlms:
  certs: