services:
    server:
        container_name: python_server
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            - TZ=Europe/Paris
        ports:
            - "4242:4242"
            - "8000:8443"
        volumes:
            - ./src:/app/src/
            - ./venv:/app/venv
            - ./storage:/storage