FROM python:3.12.5-bookworm

RUN apt-get update && apt-get install -y hashcat

ENV TZ=Europe/Paris

WORKDIR /app/src/

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src .

CMD ["python", "main.py"]