services:
    server:
        container_name: python_server
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        environment:
            - TZ=Europe/Paris
        ports:
            - "8001:8001"
            - "8000:8000"
        volumes:
            - ./src:/app/src/
            - ./venv:/app/venv