services:
    server:
        container_name: python_server
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        ports:
            - "8001:8001"
        volumes:
            - ./src:/app/src/
            - ./venv:/app/venv